import type { ApiRequest, ApiResponse } from '../_lib/http-types.js';
import { sql } from '../_lib/sql.js';
import { requireRole } from '../_lib/auth-middleware.js';

interface PayslipLine {
  category: string;
  label: string;
  amount: number;
}

interface Payslip {
  id: string;
  month: string;
  year: number;
  basicSalary: number;
  earnings: PayslipLine[];
  deductions: PayslipLine[];
  grossPay: number;
  totalDeductions: number;
  netPay: number;
  payeTax: number;
  pensionEmployee: number;
  pensionEmployer: number;
  paymentStatus: 'pending' | 'paid' | 'failed';
  paymentDate?: string;
  paymentReference?: string;
  emailed: boolean;
}

interface PayslipsResponse {
  payslips: Payslip[];
}

export default async function handler(req: ApiRequest, res: ApiResponse) {
  if (req.method !== 'GET') {
    res.setHeader('Allow', 'GET');
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const decoded = await requireRole(req, res, ['staff', 'tenant_admin']);
  if (!decoded) return;
  const staffId = decoded.staffId || decoded.userId || decoded.sub;
  if (!staffId) {
    return res.status(401).json({ error: 'Unauthorized: Invalid token payload' });
  }

  const tenantId = decoded.tenantId || 'default-tenant';

  try {
    const { month, year } = req.query;

    // Payslips are generated by the payroll engine on disbursement — join the
    // run item for the authoritative payment status/date/reference.
    const result = await sql`
      SELECT p.id::text, p.month, p.year, p.basic_salary, p.earnings, p.deductions,
        p.gross_pay, p.total_deductions, p.net_pay, p.paye_tax,
        p.pension_employee, p.pension_employer, p.emailed,
        i.status AS item_status, i.payment_date::text AS payment_date,
        i.payment_reference
      FROM payslips p
      LEFT JOIN payroll_run_items i
        ON i.run_id = p.run_id AND i.staff_id = p.staff_id AND i.tenant_id = p.tenant_id
      WHERE p.staff_id = ${staffId} AND p.tenant_id = ${tenantId}
    `;

    let payslips: Payslip[] = result.rows.map((r) => ({
      id: r.id,
      month: r.month,
      year: Number(r.year),
      basicSalary: Number(r.basic_salary),
      earnings: Array.isArray(r.earnings) ? r.earnings : [],
      deductions: Array.isArray(r.deductions) ? r.deductions : [],
      grossPay: Number(r.gross_pay),
      totalDeductions: Number(r.total_deductions),
      netPay: Number(r.net_pay),
      payeTax: Number(r.paye_tax),
      pensionEmployee: Number(r.pension_employee),
      pensionEmployer: Number(r.pension_employer),
      paymentStatus: r.item_status === 'paid' ? 'paid' : r.item_status === 'failed' ? 'failed' : 'pending',
      paymentDate: r.payment_date ?? undefined,
      paymentReference: r.payment_reference ?? undefined,
      emailed: !!r.emailed,
    }));

    if (month) {
      payslips = payslips.filter(p => p.month.toLowerCase() === (month as string).toLowerCase());
    }
    if (year) {
      payslips = payslips.filter(p => p.year === Number(year));
    }

    const monthOrder = ['January','February','March','April','May','June','July','August','September','October','November','December'];
    payslips.sort((a, b) => (b.year - a.year) || (monthOrder.indexOf(b.month) - monthOrder.indexOf(a.month)));

    const response: PayslipsResponse = { payslips };
    return res.status(200).json(response);
  } catch (error) {
    console.error('Error fetching payslips:', error);
    return res.status(500).json({ error: 'Failed to fetch payslips' });
  }
}
